#if defined _default_included
	#endinput
#endif
#define _default_included

/**
 * <library name="default" summary="Always included by the compiler.">
 *   <license>
 *     (c) Copyright 1998-2011, ITB CompuPhase
 *     This file is provided as is (no warranties).
 *   </license>
 *   <summary pawndoc="true">
 *     This library uses the enhanced <em>pawndoc.xsl</em> from
 *     <a href="https://github.com/pawn-lang/pawndoc">pawn-lang/pawndoc</a>.
 *     This XSL has features such as library and markdown support, and will not
 *     render this message when used.
 *   </summary>
 * </library>
 */

#include <core>
#include <console>

/// <p/>

